server:
  port: 8006

spring:
  application:
    name: consul-provider-payment
  #consul注册中心地址
  cloud:
    consul:
      host: 112.74.61.35
      port: 8500
      discovery:
        service-name: ${spring.application.name}